### ISSUE TITLE
Wrong xp bar location

### ISSUE THREAD

**Issue by supsm** [sidezbros/double_hotbar#1]
The experience bar is positioned too high, and overlaps the armor bar. I'm on gui scale 4, but could reproduce the issue on other scales.
![2021-12-07_23 41 42](https://user-images.githubusercontent.com/60897356/145168452-7f7629aa-fd7d-49ae-bfaa-f11d460513e9.png)
<img width="193" alt="image" src="https://user-images.githubusercontent.com/60897356/145168768-337d3272-8b87-4b70-a7dd-4f7f6a479a9e.png">

**Comment by sidezbros** [comment]
Thanks for letting me know! I have updated the mod to fix the issue. Please let me know if the issue continues to occur while using version 1.0.1
