### ISSUE TITLE
Mod isn't allowed on certain servers, please add a convienient solution

### ISSUE THREAD

**Issue by Latsi-c** [sidezbros/double_hotbar#14]
i think a whitelist and a blacklist feature should be added to the mod, its not allowed on many servers so having this feature would be very convient

**Comment by sidezbros** [comment]
I have added a setting to disable the mod. You will have to manually enable and disable the mod, but this should be much more convenient than uninstalling the mod or trying to avoid hitting your hot key. This feature is only available in v1.3.0 which is currently only for 1.18.2 and 1.19.4. If you use the 1.18.2 version make sure you update your fabric launcher to version 0.14.9
