### ISSUE TITLE
Compatibility issues with create mod on fabric

### ISSUE THREAD

**Issue by Qian-F** [sidezbros/double_hotbar#17]
https://github.com/Fabricators-of-Create/Create/issues/790

![image](https://github.com/sidezbros/double_hotbar/assets/111696321/9bc28a81-64d3-455e-a04a-7841e32b2316)

**Comment by Qian-F** [comment]
@sidezbros check this plz

**Comment by Qian-F** [comment]
3 weeks ago... if anyone don't check this
I'll close this issue

**Comment by sidezbros** [comment]
Leave the issue open. I will look into it as soon as I can. I've been out of the country most of the last two months.

**Comment by Qian-F** [comment]
> Leave the issue open. I will look into it as soon as I can. I've been out of the country most of the last two months.

thank you for your reply 
I'll wait for this bug fix

**Comment by sidezbros** [comment]
Okay I have looked into the bug and it is an issue with create. 

Create seems to be rendering the goggle tooltip twice. Once at the same time that the status bars (hearts and health) are rendered and one later. For compatibility with mods like AppleSkin that also modify the status bars, double hotbar shifts all elements that are rendered at the time of the status bars up. This means there is nothing I can do to double hotbar that will fix the issue.

Typically in create, these two tooltips are rendered on top of each other so you can't see the duplication. Double hotbar just reveals the tooltip that is being rendered at the wrong time. Create needs to remove the tooltip rendered at the time of the status bars and the issue will go away.
