### ISSUE TITLE
Game always crach because this mod when I get into a server,but I don't know why

### ISSUE THREAD

**Issue by NoNameTeam-NoNamer** [sidezbros/double_hotbar#20]
[crash-2024-02-17_15.43.17-client.txt](https://github.com/sidezbros/double_hotbar/files/14318090/crash-2024-02-17_15.43.17-client.txt)
Minecraft version is 1.20.4 and the server I join also work on 1.20.4
I didn't open shaderpack
This mod can run in my server and Single player world,
Mod version is 1.3.2,the latest version

**Comment by NoNameTeam-NoNamer** [comment]
Beacause of 1.20.4 isn't sopport? But  why I can use it on this game version?

**Comment by sidezbros** [comment]
Thanks for linking the error log. There was a rare case where a value I was expecting was not returning. Proper error handling has been added to address the issue. v1.3.2.1 is on curse forge and should fix your problem.
