### ISSUE TITLE
Items don't swap with empty slots

### ISSUE THREAD

**Issue by GitMacsi** [sidezbros/double_hotbar#24]
When I try to switch an item with an empty slot it just cancels the action, it only swaps with actual items. This might not be a bug but I think it should be an option to switch with empty slots too. I love the concept of the mod btw!

**Comment by frindaddy** [comment]
>  When I try to switch an item with an empty slot it just cancels the action, it only swaps with actual items. This might not be a bug but I think it should be an option to switch with empty slots too. I love the concept of the mod btw!

What game version and what modloader? We need more information to fix the issue. Thanks!

**Comment by GitMacsi** [comment]
It no longer happens, I don't know what could have been the problem. Sorry for the false issue
