### ISSUE TITLE
Upload 1.19 version to Modrinth

### ISSUE THREAD

**Issue by NebelNidas** [sidezbros/double_hotbar#25]
The most up-to-date releases for all the other Minecraft versions are already present, only [v1.2.3 for MC 1.19](https://www.curseforge.com/minecraft/mc-mods/double-hotbar/files/4034709) is missing.

**Comment by sidezbros** [comment]
I did not think anyone cared so I omitted it in an effort to keep the modrinth download list as clean as possible. I have uploaded it to modrinth on your request.

**Comment by NebelNidas** [comment]
Thanks! :D
