### ISSUE TITLE
1.21 - XP value overlay issue. 

### ISSUE THREAD

**Issue by Mister-Curious** [sidezbros/double_hotbar#28]
Thank you kindly for updating this mod to 1.21. I just installed the mod and noticed that the XP value is not moving above the second hotbar as in previous versions of this mod. As you can see from the screen shot, the XP value is actually overlaying the second hotbar, obscuring the view of one of the items beneath it:

![image](https://github.com/user-attachments/assets/30dced85-641c-48c6-9110-4fb38592c124)

Thank you !

**Comment by BlutVampir** [comment]
dito, but really really cool, thx for the update :)

**Comment by sidezbros** [comment]
I was testing in a new world and did not notice last night. Thanks for the catch. v1.3.3 fixes the issue and has been uploaded to Modrinth and CurseForge

**Comment by Mister-Curious** [comment]
Thank you for a quick fix! Tested and its working now.
