### ISSUE TITLE
[FEATURE] Double-tap number key to swap appropriate slot with second hotbar

### ISSUE THREAD

**Issue by unilock** [sidezbros/double_hotbar#4]
In the original [Dual Hotbar](https://www.curseforge.com/minecraft/mc-mods/dual-hotbar) mod, you could choose individual items in the second hotbar by double-tapping the appropriate number key.
It's probably impossible to replicate the same feature exactly (feel free to prove me wrong), so as a compromise, it would be nice to be able to swap individual items between appropriate slots in the first and second hotbar by double-tapping the appropriate number key for a slot.

As for implementing the same feature exactly - perhaps it would be possible to show that a slot on the second hotbar is selected on the client-side, but has actually been swapped server-side? Though I imagine this would cause some conflicts / confusion within the inventory and with other mods.

**Comment by sidezbros** [comment]
I like the idea! With the way the server side works I think you are right that just swapping the stacks is the best way to go. I have added this feature in the new 1.19 version of the mod. I also added swapping the stack in your hand by holding the swap key. Thanks for the suggestion!
