### ISSUE TITLE
Request: Height option to slice the second hotbar texture

### ISSUE THREAD

**Issue by Khodyn** [sidezbros/double_hotbar#7]
![image](https://user-images.githubusercontent.com/49518050/176810316-d5082c26-2bf7-46ce-9d58-ab9ff7fc8411.png)
To prevent transparent stacking.

**Comment by sidezbros** [comment]
[double_hotbar-1.19-v1.2.1.zip](https://github.com/sidezbros/double_hotbar/files/9024834/double_hotbar-1.19-v1.2.1.zip)
Option added. I will release publicly with 1.19.1, but in the mean time here is the beta build in a zip archive.
